version: '2'
services:

web:
  container_name: web
  image: saklyayoub/d-lamp
  restart: always
  hostname: my.localhost
  volumes:
    - $PWD/public_html:/var/www/html
  environment:
    VIRTUAL_HOST: my.localhost
    PHP_VERSION: 7.0
    PHP_MEMORY_LIMIT: 1024M
    PHP_MAX_EXECUTION_TIME: 600
    PHP_UPLOAD_MAX_FILESIZE: 64M
    PHP_POST_MAX_SIZE: 64M
    PHP_INPUT_VARS: 1500
    APACHE_PUBLIC_DIRECTORY: /var/www/html/public
    SSMTP_MAILHUB: smtp.provider.tn
    SSMTP_MAILHUB_PORT: '25'
    SSMTP_AUTH_USER: contat@myemail.me
    SSMTP_AUTH_PASS: 'kjhbkyTYFjkhbk'
    SSMTP_USE_TLS: 'NO'
    SSMTP_USE_STARTTLS: 'NO'
  ports:
    - 80:80
    - 587:587
  network_mode: bridge
